<?php

namespace Proxies\__CG__\Mautic\EmailBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class DoNotEmail extends \Mautic\EmailBundle\Entity\DoNotEmail implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Mautic\\EmailBundle\\Entity\\DoNotEmail' . "\0" . 'id', '' . "\0" . 'Mautic\\EmailBundle\\Entity\\DoNotEmail' . "\0" . 'email', '' . "\0" . 'Mautic\\EmailBundle\\Entity\\DoNotEmail' . "\0" . 'emailAddress', '' . "\0" . 'Mautic\\EmailBundle\\Entity\\DoNotEmail' . "\0" . 'lead', '' . "\0" . 'Mautic\\EmailBundle\\Entity\\DoNotEmail' . "\0" . 'dateAdded', '' . "\0" . 'Mautic\\EmailBundle\\Entity\\DoNotEmail' . "\0" . 'unsubscribed', '' . "\0" . 'Mautic\\EmailBundle\\Entity\\DoNotEmail' . "\0" . 'manual', '' . "\0" . 'Mautic\\EmailBundle\\Entity\\DoNotEmail' . "\0" . 'bounced', '' . "\0" . 'Mautic\\EmailBundle\\Entity\\DoNotEmail' . "\0" . 'comments');
        }

        return array('__isInitialized__', '' . "\0" . 'Mautic\\EmailBundle\\Entity\\DoNotEmail' . "\0" . 'id', '' . "\0" . 'Mautic\\EmailBundle\\Entity\\DoNotEmail' . "\0" . 'email', '' . "\0" . 'Mautic\\EmailBundle\\Entity\\DoNotEmail' . "\0" . 'emailAddress', '' . "\0" . 'Mautic\\EmailBundle\\Entity\\DoNotEmail' . "\0" . 'lead', '' . "\0" . 'Mautic\\EmailBundle\\Entity\\DoNotEmail' . "\0" . 'dateAdded', '' . "\0" . 'Mautic\\EmailBundle\\Entity\\DoNotEmail' . "\0" . 'unsubscribed', '' . "\0" . 'Mautic\\EmailBundle\\Entity\\DoNotEmail' . "\0" . 'manual', '' . "\0" . 'Mautic\\EmailBundle\\Entity\\DoNotEmail' . "\0" . 'bounced', '' . "\0" . 'Mautic\\EmailBundle\\Entity\\DoNotEmail' . "\0" . 'comments');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (DoNotEmail $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getComments()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComments', array());

        return parent::getComments();
    }

    /**
     * {@inheritDoc}
     */
    public function setComments($comments)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComments', array($comments));

        return parent::setComments($comments);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail(\Mautic\EmailBundle\Entity\Email $email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($email));

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getLead()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLead', array());

        return parent::getLead();
    }

    /**
     * {@inheritDoc}
     */
    public function setLead(\Mautic\LeadBundle\Entity\Lead $lead)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLead', array($lead));

        return parent::setLead($lead);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmailAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmailAddress', array());

        return parent::getEmailAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmailAddress($emailAddress)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmailAddress', array($emailAddress));

        return parent::setEmailAddress($emailAddress);
    }

    /**
     * {@inheritDoc}
     */
    public function getBounced()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBounced', array());

        return parent::getBounced();
    }

    /**
     * {@inheritDoc}
     */
    public function setBounced($bounced = true)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBounced', array($bounced));

        return parent::setBounced($bounced);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateAdded()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateAdded', array());

        return parent::getDateAdded();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateAdded($dateAdded)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateAdded', array($dateAdded));

        return parent::setDateAdded($dateAdded);
    }

    /**
     * {@inheritDoc}
     */
    public function getUnsubscribed()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUnsubscribed', array());

        return parent::getUnsubscribed();
    }

    /**
     * {@inheritDoc}
     */
    public function setUnsubscribed($unsubscribed = true)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUnsubscribed', array($unsubscribed));

        return parent::setUnsubscribed($unsubscribed);
    }

    /**
     * {@inheritDoc}
     */
    public function isManual()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isManual', array());

        return parent::isManual();
    }

    /**
     * {@inheritDoc}
     */
    public function setManual($manual = true)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setManual', array($manual));

        return parent::setManual($manual);
    }

}
